name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # o master, según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          echo 'export const environment = {' > src/environments/environments.ts
          echo '  production: true,' >> src/environments/environments.ts
          echo '  rapidApi: {' >> src/environments/environments.ts
          echo '    key: "${{ secrets.RAPID_API_KEY }}",' >> src/environments/environments.ts
          echo '    host: "${{ secrets.RAPID_API_HOST }}"' >> src/environments/environments.ts
          echo '  }' >> src/environments/environments.ts
          echo '};' >> src/environments/environments.ts

      - name: Build
        run: npm run build -- --configuration production --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/bci-challenge  # carpeta donde se genera el build
          branch: gh-pages