# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup nodeJS
      - name: Setup node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "18"

      # 3. Modifica Environment
      - name: Modifica Environment
        run: |
          echo "export const environment = {" > ./src/environments/environment.ts
          echo "  production: true," >> ./src/environments/environment.ts
          echo "  rapidApi: {" >> ./src/environments/environment.ts
          echo "    key: '${{ secrets.RAPIDAPI_KEY }}'," >> ./src/environments/environment.ts
          echo "    host: '${{ secrets.RAPIDAPI_HOST }}'" >> ./src/environments/environment.ts
          echo "  }" >> ./src/environments/environment.ts
          echo "};" >> ./src/environments/environment.ts

      # 4. Instalar dependencias desde Azure Artifacts
      - name: Install deps
        run: npm i

      # 5. Build app for production
      - name: Build app bundle
        run: npm run build:prod

      # 6. Route file renaming
      - name: Rename index for routing
        run: mv dist/bci-challenge/index.html dist/bci-challenge/404.html

      # 7. Deploy to GitHub
      - name: Deploy to Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/bci-challenge
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
